upload_max_filesize = 30M
post_max_size = 30M

memory_limit = 256M
max_execution_time = 300

display_errors = Off
log_errors = On

date.timezone = Europe/Paris

extension=/usr/lib/php83/modules/pdo_mysql.so
extension=/usr/lib/php83/modules/mysqli.so
